oficios/apps/Stalkers/urls.py
from django.urls import path, include
from . import views

app_name='Stalkers'

urlpatterns = [
    path('Registro',views.Registro.as_view(),name='registro'),
    path('EditarPerfil/<str:pk>',views.EditarPerfil.as_view(),name='editarPerfil'),
]

oficios/apps/Trabajadores/urls.py
from django.urls import path, include
from . import views

app_name='Trabajadores'

urlpatterns = [
    path('Registro',views.Registro.as_view(),name='registro'),
    path('Listar',views.Listar.as_view(),name='Listar'),
    path('EditarPerfil/<str:pk>',views.EditarPerfil.as_view(),name='editarPerfil'),
    path('MostrarPerfil/<str:pk>', views.MostrarPerfil.as_view(), name='mostrarPerfil'),
    path('filtroZona', views.ajaxTrabajador, name='filtroZona'),



]   

oficios/apps/Usuarios/urls.py
from django.urls import path, include
from . import views

app_name='Usuarios'
urlpatterns = [
    path('Perfil',views.Perfil,name='perfil'),
    path('BorrarPerfil/<str:pk>', views.BorrarPerfil.as_view(), name='BorrarPerfil'),
]

oficios/oficios/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.conf import settings

#URL PRINCIPAL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='Home'),
    path('Usuarios/',include('apps.Usuarios.urls')),
    path('Trabajadores/',include('apps.Trabajadores.urls')),
    path('Stalkers/',include('apps.Stalkers.urls')),
    path('Comentarios/',include('apps.Comentarios.urls')),
    path('Zonas/',include('apps.Zonas.urls')),
    path('Calificaciones/',include('apps.Calificaciones.urls')),
    path('Login', auth.LoginView.as_view(template_name='Usuarios/Login.html'), name='login'),
    path('Logout', auth.LogoutView.as_view(template_name='Usuarios/Logout.html'), name='logout'),

    path('password', auth.PasswordChangeView.as_view(template_name='Usuarios/password.html'), name='password_change'),
    path('passwordDone', auth.PasswordChangeDoneView.as_view(template_name='Usuarios/passwordDone.html'), name='password_change_done'),
    path('reset_password/',
        auth.PasswordResetView.as_view(template_name="Usuarios/password_reset.html"), 
        name="reset_password"),

    path('reset_password_sent/',
        auth.PasswordResetDoneView.as_view(template_name="Usuarios/password_reset_sent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth.PasswordResetConfirmView.as_view(template_name="Usuarios/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth.PasswordResetCompleteView.as_view(template_name="Usuarios/password_reset_done.html"), 
        name="password_reset_complete"),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

oficios/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        
        <!--datables estilo bootstrap 4 CSS-->  
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        
        
        <link rel="icon" type="image/x-icon" href="{% static 'assets/ico/favicon_proyecto/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href='{% static "datatables/datatables.min.css" %}'/>
        <link rel="stylesheet"  type="text/css" href="{% static 'datatables/DataTables-1.10.22/css/dataTables.bootstrap4.min.css' %}">  

        <link rel="stylesheet" href=" {% static 'css/styles.css' %}">
        <link rel="stylesheet" href=" {% static 'css/profile.css' %}">
        {% block title %} <title>Base</title>{% endblock %}
    </head>
        <body id="page-top">
        {% block nav %}
        <!--Barra de navegacion-->

        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger work workhub" href="#page-top"></a>
                <a class="navbar-brand" href="{% url 'Home' %}"><i class="fas fa-home hola">
                <span class="soyhome">Hola gente soy el home</span> 
                </i></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item" style="margin:10px;">
                                <a href="{% url 'Usuarios:perfil' %}" role="button" class="btn btn-warning" >

                                            <i class="fas fa-user-alt"></i>

                                        <span> Hola {{user.first_name}}</span>                                    
                                </a>                                
                            </li>
                            
                            <li class="nav-item" style="margin:10px;">
                                <a href="{% url 'logout' %}" role="button" class="btn btn-warning" >
                                    <i class="fas fa-sign-out-alt"></i>
                                    Logout
                                </a>                                
                            </li>
                            
                        {% else %}
                            <li class="nav-item" style="margin:10px;">
                                <a href="{% url 'login' %}" role="button" class="btn btn-warning" >
                                    <i class="fas fa-sign-in-alt"></i>
                                    Login
                                </a>                                
                            </li>
                            <li class="nav-item"  style="margin:10px;">
                                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#RegistroModal">
                                    <i class="fas fa-user-plus"></i>
                                    Registrarse
                                </button>
                        {% endif %}
                        <li class="nav-item" style="margin:10px;">
                            <a href="{% url 'Trabajadores:Listar' %}" role="button" class="btn btn-warning" data-target="">
                                <i class="fas fa-table"></i>
                                Trabajadores
                            </a>                                
                        </li>
                        
                    </ul>
                </div>
            </div>           
        </nav>
        {% endblock %}

        <!-- Supercontent-->
        {% block content %}
            
        {% endblock %}
       
        <!--Modal de registro-->
        <div class="modal fade" id="RegistroModal" tabindex="-1" role="dialog" aria-labelledby="Registro" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Registro</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                <p>Es usted un trabajador?</p>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-primary registro" id='TrabajadoresR'
                data-url="{% url 'Trabajadores:registro' %}">Si</button>
                <button type="button" class="btn btn-secondary registro" id='StalkersR'
                data-url="{% url 'Stalkers:registro' %}">No</button>
                </div>
            </div>
            </div>
        </div>   

        <!--Zona de scripts-->
        
        
        <script src="https://unpkg.com/@popperjs/core@2"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        
        <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
        
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        
        <!-- Third party plugin JS-->

        <!-- Core theme JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>  <!-- JQUERY HERE -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.js"></script>
        <script type="text/javascript" src="{% static 'datatables/datatables.min.js' %}"></script>
        <script src=" {% static 'js/scripts.js' %}"></script>
        <script src=" {% static 'js/datatables.js' %}"></script>
        {% block js %} 
        
        
        {% endblock %}
        
           

    </body>



</html>

oficios/templates/Home.html
{% extends "base.html" %}

{% block title %}
<title> HOME </title>
{% endblock title %}

        
{% block content %}
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Bienvenidos a WorkHub</h1>
                <h3 class="text-white font-weight-bold">Trabajamos y nos divertimos</h3>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light ">Comience su busqueda de una persona especialista en su rubo.</p>
                <p class="text-white-75 font-weight-light ">Estas instalando el split solo en casa?</p>
                <p class="text-white-75 font-weight-light mb-5">Ya no mas haciendo click abajo.</p>
                <a href="{% url 'Trabajadores:Listar' %}" role="button" class="btn btn-primary btn-xl js-scroll-trigger" data-target="">
                    <i class="fas fa-table"></i>
                    Trabajadores
                </a>
            </div>
        </div>
    </div>
</header>
{% endblock content %}