oficios/apps/Calificaciones/urls.py
from django.urls import path
from . import views

app_name='Calificaciones'

urlpatterns = [
    path('Calificar/<str:pk>/', views.Calificar.as_view(), name = 'Calificar'),
]

oficios/oficios/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.conf import settings

#URL PRINCIPAL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='Home'),
    path('Usuarios/',include('apps.Usuarios.urls')),
    path('Trabajadores/',include('apps.Trabajadores.urls')),
    path('Stalkers/',include('apps.Stalkers.urls')),
    path('Comentarios/',include('apps.Comentarios.urls')),
    path('Zonas/',include('apps.Zonas.urls')),
    path('Calificaciones/',include('apps.Calificaciones.urls')),
    path('Login', auth.LoginView.as_view(template_name='Usuarios/Login.html'), name='login'),
    path('Logout', auth.LogoutView.as_view(template_name='Usuarios/Logout.html'), name='logout'),

    path('password', auth.PasswordChangeView.as_view(template_name='Usuarios/password.html'), name='password_change'),
    path('passwordDone', auth.PasswordChangeDoneView.as_view(template_name='Usuarios/passwordDone.html'), name='password_change_done'),
    path('reset_password/',
        auth.PasswordResetView.as_view(template_name="Usuarios/password_reset.html"), 
        name="reset_password"),

    path('reset_password_sent/',
        auth.PasswordResetDoneView.as_view(template_name="Usuarios/password_reset_sent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth.PasswordResetConfirmView.as_view(template_name="Usuarios/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth.PasswordResetCompleteView.as_view(template_name="Usuarios/password_reset_done.html"), 
        name="password_reset_complete"),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

oficios/apps/Calificaciones/models.py
from django.db import models
from ..Trabajadores.models import Trabajadores
from ..Stalkers.models import Stalkers

valores=[(1,1),(2,2),(3,3),(4,4),(5,5)]
class Calificaciones(models.Model):
    trabajador = models.ForeignKey(Trabajadores,on_delete=models.CASCADE,related_name='calificado')
    stalker = models.ManyToManyField(Stalkers,related_name='califica',blank=True)
    calificacion = models.PositiveSmallIntegerField(choices=valores)
    comentario = models.TextField(default=None,null=True,blank=True)
    
    def __str__(self):
        return str(self.calificacion)

oficios/apps/Calificaciones/forms.py
from django.forms import ModelForm, RadioSelect
from .models import Calificaciones

class CalificacionesForm(ModelForm):
    class Meta:
        model=Calificaciones
        fields=['calificacion']
        ordering=['calificacion']
        empty=None
        widgets = {
            'calificacion': RadioSelect(),
        }
    def save(self,commit=False):
        calificacion=super().save(commit)
        return calificacion

oficios/apps/Calificaciones/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from ..utils.funciones import PermisosMixin,PasajeMixin
from .forms import CalificacionesForm
from ..Trabajadores.models import Trabajadores
from .models import Calificaciones
from django.db.models import Avg

class Calificar(LoginRequiredMixin,PermisosMixin,PasajeMixin,CreateView):
    model=Calificaciones
    form_class=CalificacionesForm
    template_name='Calificaciones/Calificar.html'
    rol='stalker'
    campos=['perfil','objeto']

    def tratar_perfil(self,perfil,form,instancia,objeto):
        form.save(commit=True)
        instancia.stalker.add(perfil)
        avg=Calificaciones.objects.filter(trabajador=objeto).aggregate(Avg('calificacion'))
        objeto.promedio = avg['calificacion__avg']
        objeto.save()

oficios/templates/Calificaciones/Calificar.html
{% load static %}

	
	<form method="POST" action="{% url 'Calificaciones:Calificar' object.pk %}">
	{% csrf_token %}
	  
		<div style="float: left;" class="valoracion">
				<div class="form-check">
					<input class="form-check-input star" type="radio"  name="calificacion" value="5" id="id_calificacion_5" required>

					<label class="form-check-label star" for="id_calificacion_5">
						
							<i class="fas fa-star"></i>

					</label>
				</div>
				
				<div class="form-check">
					<input class="form-check-input star" type="radio" name="calificacion" value="4" id="id_calificacion_4" required>
					<label class="form-check-label star" for="id_calificacion_4">
						
							<i class="fas fa-star"></i>

					</label>
				</div>
				
				<div class="form-check">
					<input class="form-check-input star" type="radio" name="calificacion" value="3" id="id_calificacion_3" required>
					<label class="form-check-label star" for="id_calificacion_3">

						
							<i class="fas fa-star"></i>

					</label>
				</div>
				
				<div class="form-check">
					<input class="form-check-input star" type="radio" name="calificacion" value="2" id="id_calificacion_2" required>

					<label class="form-check-label star" for="id_calificacion_2">
						
							<i class="fas fa-star"></i>

						
					</label>
				</div>
				
				<div class="form-check">
					<input class="form-check-input star" type="radio" name="calificacion" value="1" id="id_calificacion_1" required>
					<label class="form-check-label star" for="id_calificacion_1">
						
							<i class="fas fa-star"></i>

					</label>
				
				</div>

				<input type="submit" class="btn btn-success" value="Calificar" >
							
		</div>	
	</form>

	