oficios/apps/Usuarios/urls.py
from django.urls import path, include
from . import views

app_name='Usuarios'
urlpatterns = [
    path('Perfil',views.Perfil,name='perfil'),
    path('BorrarPerfil/<str:pk>', views.BorrarPerfil.as_view(), name='BorrarPerfil'),
]

oficios/oficios/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.conf import settings

#URL PRINCIPAL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='Home'),
    path('Usuarios/',include('apps.Usuarios.urls')),
    path('Trabajadores/',include('apps.Trabajadores.urls')),
    path('Stalkers/',include('apps.Stalkers.urls')),
    path('Comentarios/',include('apps.Comentarios.urls')),
    path('Zonas/',include('apps.Zonas.urls')),
    path('Calificaciones/',include('apps.Calificaciones.urls')),
    path('Login', auth.LoginView.as_view(template_name='Usuarios/Login.html'), name='login'),
    path('Logout', auth.LogoutView.as_view(template_name='Usuarios/Logout.html'), name='logout'),

    path('password', auth.PasswordChangeView.as_view(template_name='Usuarios/password.html'), name='password_change'),
    path('passwordDone', auth.PasswordChangeDoneView.as_view(template_name='Usuarios/passwordDone.html'), name='password_change_done'),
    path('reset_password/',
        auth.PasswordResetView.as_view(template_name="Usuarios/password_reset.html"), 
        name="reset_password"),

    path('reset_password_sent/',
        auth.PasswordResetDoneView.as_view(template_name="Usuarios/password_reset_sent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth.PasswordResetConfirmView.as_view(template_name="Usuarios/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth.PasswordResetCompleteView.as_view(template_name="Usuarios/password_reset_done.html"), 
        name="password_reset_complete"),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

oficios/apps/Usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy


class Usuarios(AbstractUser):
	Trabajador=models.BooleanField(default=False)
	address=models.CharField(max_length=60,null=True)
	phone=models.BigIntegerField(null=True)
	
	#Obtener los datos del usuario para mostrarlos
	def ObtenerDatos(self):
		cositas={'Usuario':self.username,'Nombre':self.first_name,'Apellido':self.last_name,'Email':self.email,
		'Direccion':self.address,'Telefono':self.phone}
		
		return cositas
		
	#Obtener el pk si el usuario es un trabajador o un stalker
	def ObtenerPk(self):
		if(self.Trabajador):
			return self.Worker.pk
		return self.Stalker.pk

	def ObtenerPerfil(self):
		if(self.Trabajador):
			return self.Worker
		return self.Stalker

oficios/apps/Usuarios/forms.py
from django.forms import ModelForm
from . import models

class UsuariosForm(ModelForm):
    class Meta:
        model=models.Usuarios
        fields='__all__'

oficios/apps/Usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse_lazy
from . import models
# Create your views here.
@login_required
def Perfil(request):
    return render(request,'Usuarios/Perfil.html')

class BorrarPerfil(generic.DeleteView):
    model = models.Usuarios
    template_name = 'Usuarios/BorrarPerfil.html'
    success_url = reverse_lazy('logout')

oficios/templates/Usuarios/BorrarPerfil.html
<form method="post">{% csrf_token %} 
    <p>Esta seguro de eliminar el perfil ??  "{{ object }}"?</p> 
    <input type="submit" value="Confirm"> 
</form> 

oficios/templates/Usuarios/EditarPerfil.html
{% extends "Base.html" %}
{% block title %}
<title> <- Editar Perfil - {{user.username}} -> </title>
{% endblock title %}
{% block content %}
<header class="editPerfilHeader">
    </header>
    <div class="container h-100">
        {%if form.errors %} 
            <div class="alert alert-primary" role="alert">
                {{form.errors}}
            </div>
        {%endif%}  
        <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}    
            <div class="jumbotron">
                <h2 class="display-4">Editar {{user.username}}</h2>
                <hr>
                <br>    
                
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.first_name.errors }}
                        {{ form.first_name.label_tag }} {{ form.first_name }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.last_name.errors }}
                        {{ form.last_name.label_tag }} {{ form.last_name }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.username.errors }}
                        {{ form.username.label_tag }} {{ form.username }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.email.errors }}
                        {{ form.email.label_tag }} {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.phone.errors }}
                        {{ form.phone.label_tag }} {{ form.phone }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.address.errors }}
                        {{ form.address.label_tag }} {{ form.address }}
                    </div>
                    
                </div>
                {% if user.Trabajador %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.especialidad.errors }}
                        {{ form.especialidad.label_tag }} {{ form.especialidad }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.rubro.errors }}
                        {{ form.rubro.label_tag }} {{ form.rubro }}
                    </div>
                    
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.certificado.errors }}
                        {{ form.certificado.label_tag }} {{ form.certificado }}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.zonas.errors }}
                        {{ form.zonas.label_tag }} {{ form.zonas }}
                    </div>
                    
                </div>
                {% endif %}
                
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {{ form.password }}
                        <p class="help">El sistema no almacena las contraseñas originales 
                            por lo cual no es posible visualizar la contraseña de este usuario, 
                            pero puede modificarla usando <a href="{% url 'password_change' %}">este formulario</a>.</p>
                </div>
                </div>
                

                
                <center><input type="submit"  class="btn btn-primary" value="Validar Cambios"></center>
                
            </div>
        </form>
    </div>
{% endblock content %}

oficios/templates/Usuarios/Login.html
{% extends 'Home.html' %}

{% block title %}

<title>Login</title>

{% endblock title %}


{% block content %}
<body class="loginBody">
    <div class="container h-100">
        <body class="mastbody">
            <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
            <form method="POST">
                {% csrf_token %}
                <div class="container login">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Usuario</label>
                        <input id="exampleInputEmail1" type="text" name="username" class="form-control"  placeholder="Usuario">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Contraseña</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password"  placeholder="Contraseña">
                    </div>
                    
                    <input type="submit" class="btn btn-primary"  name="" value="Ingresar">
                    <br>
                    <br>
                    <div class="d-flex-justify-content-center-links">
                        <a href="{% url 'reset_password' %}">Restablecer Contraseña</a>            
                    </div>
                    
                    <input type="hidden" name="next" value="{{next}}">
                    {% if form.errors %}
                    <div class="container" style="padding: 15px; text-align: left;">
                        <p class="text-danger">Su usuario y/o contraseña no son válidos</p>
                    </div>
                    </div>
                    {% endif%}
            </form>
        </div>
    </div>
</body>
{% endblock content %}

oficios/templates/Usuarios/Perfil.html
{% extends "Base.html" %}
{% load usuario_url %}
{% block title %}
<title> Perfil </title>
{% endblock title %}
{% block content %}
<header class="perfilhead"> </header>
<br>
<br>
<br>
    <div class="container">   

                <div class="row text-center">
                    
                        {% if user.Worker.certificado %}
                        <div class="col-md-4">
                        <div class="profile-img">
                            <img src="{{user.Worker.certificado.url}}" alt=""/>
                            
                        </div>
                    </div>
                        {% endif %}
                        
                        {% if user.Trabajador %}
                    <div class="col-md-4">
                        {% else %}
                        <div class="col-md-8">
                                    {% endif %}
                        <div class="profile-head">
                                    <h3>
                                        {{user.first_name}} {{user.last_name}}
                                    </h3>
                                    {% if user.Trabajador %}
                                    <h6>
                                        {{user.Worker.especialidad}}
                                    </h6>
                                    <p class="proile-rating">RANKINGS : <span>{{user.Worker.promedio|floatformat:"0"}}/5</span></p>   
                                    {% else %}
                                    <br><br>
                                    {% endif %}
                        
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button id="EditarPerfil" class="btn btn-warning profile-edit-btn"
                        data-url="{% url user|ObtenerUrl:'editarPerfil' user.pk %}">
                            Editar
                        </button>
                    
                    </div>
                    <div class="col-md-2">
                        <button type="button" class="btn btn-danger profile-delete-btn" data-toggle="modal" 
                        data-target="#BajaModal">
                            <i class="fas fa-trash-plus"></i>
                            Darse de baja
                        </button>
                    </div>
                    
                </div>
                <div class="row text-center">
                    {% if user.Trabajador %}
                    <div class="col-md-4">
                        
                        <div class="profile-work">

                            <p class="font-weight-bold">Rubro: <span>{{user.Worker.rubro}}</span></p>
                            <p>Zonas</p>
                            {% for z in user.Worker.zonas.all  %}
                            <p><span >{{z}}</span></p>
                            {% endfor %}
                        </div>
                        
                        
                    </div>
                    
                    <div class="col-md-8">
                        {% else %}
                        <div class="col-md-12">
                        {% endif %}
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                {% for label,datos in user.ObtenerDatos.items  %}
                                {% if datos %}
                                    <div class="row text-left">            
                                        <div class="col-md-6">
                                            <label>{{label}}: </label>
                                        </div>                
                                        <div class="col-md-6 text-right">
                                                            
                                            <p>{{datos}}</p>
        
                                        </div>
                                    </div>    
                                {% endif %}
                            {% endfor %}
                            </div>
                        
                        </div>
                    </div>
                </div>       
        </div> 
            
            
        <!--Modal de registro-->
        <div class="modal fade" id="BajaModal" tabindex="-1" role="dialog" aria-labelledby="Registro" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Darse de baja</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form method="post" action="{% url 'Usuarios:BorrarPerfil' user.pk %}">{% csrf_token %} 
                <div class="modal-body">
                <p>{{user.username}} - Esta seguro que quiere eliminar su cuenta? </p>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-danger" value="Si"> 
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
            </form> 
            </div>
            </div>

    </div>
{% endblock content %}

oficios/templates/Usuarios/Registro.html
{% extends "Base.html" %}
{% block title %}
<title> <<< Registro >>> </title>
{% endblock title %}
{% block content %}

<header class="registroHead">
    </header>
    <div class="container h-100">
    {%if form.errors %} 
        <div class="alert alert-primary" role="alert">
            {{form.errors}}
        </div>
    {%endif%}  
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="jumbotron">
            <h1 class="display-4">Registrate ya {{ usuario }}!!!</h1>
            <hr>
            <br>    
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.first_name.errors }}
                    {{ form.first_name.label_tag }} {{ form.first_name }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.last_name.errors }}
                    {{ form.last_name.label_tag }} {{ form.last_name }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.username.errors }}
                    {{ form.username.label_tag }} {{ form.username }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.email.errors }}
                    {{ form.email.label_tag }} {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.password1.errors }}
                    {{ form.password1.label_tag }} {{ form.password1 }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.password2.errors }}
                    {{ form.password2.label_tag }} {{ form.password2 }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.phone.errors }}
                    <label for="">Teléfono:</label> {{ form.phone }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.address.errors }}
                    <label for="">Dirección:</label> {{ form.address }}
                </div>
                
            </div>

            {%  if usuario == "Trabajador" %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.Especialidad.errors }}
                    {{ form.Especialidad.label_tag }} {{ form.Especialidad }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.Rubro.errors }}
                    {{ form.Rubro.label_tag }} {{ form.Rubro }}
                </div>
                
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.Certificado.errors }}
                    {{ form.Certificado.label_tag }} {{ form.Certificado }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.zonas.errors }}
                    {{ form.zonas.label_tag }} {{ form.zonas }}
                </div>
                
            </div>
                    
            {%endif%}
            <hr>
            <center><input type="submit"  class="btn btn-primary" value="Registrarse"></center>
            <hr>
        </div>
    
    </form>
</div>

{% endblock %}

oficios/templates/Usuarios/password.html
{% extends "Base.html" %}

{% block content %}
<body class="loginBody">
    <div class="container h-100">
        <body class="mastbody">
            <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
<form method="post">
    {% csrf_token %}
    <div class="container login">
        <p>{{form.errors}}</p>
        
        <label for="id_old_password">Contraseña antigua:</label>
    <input class="form-control" type="password" name="old_password" autocomplete="current-password" autofocus="" required="" id="id_old_password">
    <label for="id_new_password1">Contraseña nueva:</label>
    <input class="form-control" type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1">
    <br>
    <span class="helptext"><ul><li>Su contraseña no puede ser similar a otros componentes de su información personal.</li><li>Su contraseña debe contener por lo menos 8 caracteres.</li><li>Su contraseña no puede ser una contraseña usada muy comúnmente.</li><li>Su contraseña no puede estar formada exclusivamente por números.</li></ul></span>
    <label for="id_new_password2">Confirmación de contraseña nueva:</label>
    <input class="form-control" type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2">
    <br>
   <input type="Submit" value="Actualizar Password" class="btn btn-primary" >
    </div>
    
</form>
            </div>
            </div>
        </body>
    </div>
</body>
{% endblock content %}

oficios/templates/Usuarios/passwordDone.html
{% extends "Base.html" %}

{% block content %}
<body class="loginBody">

        <body class="mastbody">

            <div class="row h-100 align-items-center justify-content-center text-center">

                    <a href="/" class="messirve"></a>
 
            </div>

        </body>

</body>
{% endblock content %}

oficios/templates/Usuarios/password_reset.html
{% extends 'base.html' %}

{% block content %}
<body class="loginBody">
  <div class="container h-100">
      <body class="mastbody">
          <div class="container h-100">
<div class="row h-100 align-items-center justify-content-center text-center">
	<div class="jumbotron">
<h3>Restablecer Contraseña</h3>
<p>¿Olvidó su contraseña? Ingrese su dirección de email y enviaremos las instrucciones para su recuperación.</p>

<form method="POST">

    {% csrf_token %}
    <div class="form-group">
    	<label for="id_email">Email:</label>
		<input type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" class="form-control">
		<br>
    <input type="Submit" name="Enviar" class="btn btn-primary">
    </div>
</form>

</div>
</div>
          </div>
      </body>
  </div>
</body>
{% endblock %}

oficios/templates/Usuarios/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<body class="loginBody">
    <div class="container h-100">
        <body class="mastbody">
            <div class="container h-100">
<div class="row h-100 align-items-center justify-content-center text-center">
	<div class="jumbotron">
<h3>Su contraseña se ha restablecido correctamente.</h3>
<p>Ahora puede iniciar sesion en el link</p>
<a href="{% url 'login' %}">Login</a>
	</div>
</div>
			</div>
		</body>
	</div>
</body>
{% endblock %}

oficios/templates/Usuarios/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<body class="loginBody">
    <div class="container h-100">
        <body class="mastbody">
            <div class="container h-100">
<div class="row h-100 align-items-center justify-content-center text-center">
	<div class="jumbotron">
<h3>Ingrese Nuevo Password</h3>
<p>Ingrese y confirme ambos password correctamente</p>

<form method="POST">
    
    {% csrf_token %}
   <label for="id_new_password1">Contraseña nueva:</label>
   <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1" aria-autocomplete="list" class="form-control">
   <span class="helptext"><ul><li>Su contraseña no puede ser similar a otros componentes de su información personal.</li><li>Su contraseña debe contener por lo menos 8 caracteres.</li><li>Su contraseña no puede ser una contraseña usada muy comúnmente.</li><li>Su contraseña no puede estar formada exclusivamente por números.</li></ul></span>
   <label for="id_new_password2">Confirmación de contraseña nueva:</label>
   <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2" class="form-control">
   <br>
   <input type="Submit" value="Actualizar Password" class="btn btn-primary" >

</form>
	</div>
    </div>
            </div>
        </body>
    </div>
</body>
{% endblock %}

oficios/templates/Usuarios/password_reset_sent.html
{% extends 'base.html' %}

{% block content %}
<body class="loginBody">
    <div class="container h-100">
        <body class="mastbody">
            <div class="container h-100">
<div class="row h-100 align-items-center justify-content-center text-center">
	<div class="jumbotron">
<p>Enviamos a su correo el link para restablecer su contraseña, verifíquelo.</p>
<p>Si no recibió el correo, verifique en la carpeta "SPAM"</p>
	</div>
</div>
			</div>
		</body>
	</div>
</body>
{% endblock %}