oficios/apps/Stalkers/urls.py
from django.urls import path, include
from . import views

app_name='Stalkers'

urlpatterns = [
    path('Registro',views.Registro.as_view(),name='registro'),
    path('EditarPerfil/<str:pk>',views.EditarPerfil.as_view(),name='editarPerfil'),
]

oficios/apps/Trabajadores/urls.py
from django.urls import path, include
from . import views

app_name='Trabajadores'

urlpatterns = [
    path('Registro',views.Registro.as_view(),name='registro'),
    path('Listar',views.Listar.as_view(),name='Listar'),
    path('EditarPerfil/<str:pk>',views.EditarPerfil.as_view(),name='editarPerfil'),
    path('MostrarPerfil/<str:pk>', views.MostrarPerfil.as_view(), name='mostrarPerfil'),
    path('filtroZona', views.ajaxTrabajador, name='filtroZona'),



]   

oficios/apps/Usuarios/urls.py
from django.urls import path, include
from . import views

app_name='Usuarios'
urlpatterns = [
    path('Perfil',views.Perfil,name='perfil'),
    path('BorrarPerfil/<str:pk>', views.BorrarPerfil.as_view(), name='BorrarPerfil'),
]

oficios/oficios/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.conf import settings

#URL PRINCIPAL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='Home'),
    path('Usuarios/',include('apps.Usuarios.urls')),
    path('Trabajadores/',include('apps.Trabajadores.urls')),
    path('Stalkers/',include('apps.Stalkers.urls')),
    path('Comentarios/',include('apps.Comentarios.urls')),
    path('Zonas/',include('apps.Zonas.urls')),
    path('Calificaciones/',include('apps.Calificaciones.urls')),
    path('Login', auth.LoginView.as_view(template_name='Usuarios/Login.html'), name='login'),
    path('Logout', auth.LogoutView.as_view(template_name='Usuarios/Logout.html'), name='logout'),

    path('password', auth.PasswordChangeView.as_view(template_name='Usuarios/password.html'), name='password_change'),
    path('passwordDone', auth.PasswordChangeDoneView.as_view(template_name='Usuarios/passwordDone.html'), name='password_change_done'),
    path('reset_password/',
        auth.PasswordResetView.as_view(template_name="Usuarios/password_reset.html"), 
        name="reset_password"),

    path('reset_password_sent/',
        auth.PasswordResetDoneView.as_view(template_name="Usuarios/password_reset_sent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth.PasswordResetConfirmView.as_view(template_name="Usuarios/password_reset_form.html"), 
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth.PasswordResetCompleteView.as_view(template_name="Usuarios/password_reset_done.html"), 
        name="password_reset_complete"),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

oficios/apps/Trabajadores/models.py
from django.db import models
from ..Usuarios.models import Usuarios
from ..Zonas.models import Zonas

class Rubros(models.Model):
    nombre=models.CharField(max_length=20)
    
    def __str__(self):
        return self.nombre

class Trabajadores(models.Model):
    usuario= models.OneToOneField(Usuarios,on_delete=models.CASCADE,related_name='Worker')
    promedio= models.FloatField(default=0)
    especialidad= models.CharField(max_length=50)
    certificado = models.ImageField(upload_to='Trabajadores',null=True,blank=True)
    rubro = models.ForeignKey(Rubros,null=True,on_delete=models.SET_NULL,related_name='filtro_rubro')
    zonas = models.ManyToManyField(Zonas,related_name='Opera',blank=True)

    def __str__(self):
        return self.usuario.username

oficios/apps/Usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy


class Usuarios(AbstractUser):
	Trabajador=models.BooleanField(default=False)
	address=models.CharField(max_length=60,null=True)
	phone=models.BigIntegerField(null=True)
	
	#Obtener los datos del usuario para mostrarlos
	def ObtenerDatos(self):
		cositas={'Usuario':self.username,'Nombre':self.first_name,'Apellido':self.last_name,'Email':self.email,
		'Direccion':self.address,'Telefono':self.phone}
		
		return cositas
		
	#Obtener el pk si el usuario es un trabajador o un stalker
	def ObtenerPk(self):
		if(self.Trabajador):
			return self.Worker.pk
		return self.Stalker.pk

	def ObtenerPerfil(self):
		if(self.Trabajador):
			return self.Worker
		return self.Stalker

oficios/apps/Trabajadores/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms
from .models import Trabajadores,Rubros
from ..Zonas.models import Zonas
from ..Usuarios.models import Usuarios
from django.db import transaction

#ALTA------------------------------------
#Se hereda del UserCreationForm ya que cuenta con todo el tema de validaciones para el create de un usuario
#Formulario de registrar un trabajador
class TrabajadoresForm(UserCreationForm):
    #Campos que son del trabajador y por ende no estan en el usuario
    #Se lo tiene que poner a mano
    Especialidad=forms.CharField(max_length=50)
    Rubro=forms.ModelChoiceField(Rubros.objects.all())
    Certificado=forms.ImageField(required=False)
    zonas=forms.ModelMultipleChoiceField(Zonas.objects.all())
    
    class Meta:
        model=Usuarios
        fields=['first_name','last_name','username','password1','password2','email','phone','address']

    def __init__(self, *args, **kwargs):
        super(TrabajadoresForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.name!='Certificado':
                visible.field.widget.attrs['class'] = 'form-control'        
        
#Se redefine el save ya que los unicos datos que se guardan son del modelo que se asigna en el Meta
#Por ende hay que crear un trabajador a mano en este metodo
    @transaction.atomic
    def save(self):
        usuario=super().save(commit=False)
        usuario.Trabajador=True
        usuario.save()
        job = Trabajadores.objects.create(usuario=usuario,       
        especialidad=self.cleaned_data.get('Especialidad'),rubro=self.cleaned_data['Rubro'],
        certificado=self.cleaned_data['Certificado'])
        zone=self.cleaned_data['zonas']
        for z in zone:
            job.zonas.add(z)
        
        job.save()

        return usuario


        
#UPDATE-----------------------------------------
#Se hereda del UserChangeForm ya que cuenta con todo el tema de validaciones para el update de un usuario
#Formulario de editar el perfil de un trabajador
class EditarForm(UserChangeForm):
    #Campos que son del trabajador y por ende no estan en el usuario
    especialidad=forms.CharField(max_length=50)
    rubro=forms.ModelChoiceField(Rubros.objects.all())
    certificado=forms.ImageField(required=False)
    zonas=forms.ModelMultipleChoiceField(Zonas.objects.all())

    class Meta: #Se ocupa el modelo usuario para que django se encargue de las validaciones
        model=Usuarios
        fields=['first_name','last_name','username','email','phone','address']
        

#Se redefine el init para mostrar los datos de la instancia en los campos que no son del modelo usuario
#kwargs['instance'] tiene la instancia del modelo en ese momento, en este caso usuario
#Con la relacion Worker se accede a los datos de los campos del trabajador
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['especialidad'].initial=kwargs['instance'].Worker.especialidad
        self.fields['rubro'].initial=kwargs['instance'].Worker.rubro
        self.fields['certificado'].initial=kwargs['instance'].Worker.certificado
        self.fields['zonas'].initial=kwargs['instance'].Worker.zonas.all()
        for visible in self.visible_fields():
            if visible.name != 'password' and visible.name!='certificado':
                visible.field.widget.attrs['class'] = 'form-control'
        
        

#Se redefine el Save porque lo unico que se guardaria son los campos del usuario y no los del trabajador
    @transaction.atomic
    def save(self):
        usuario=super().save(commit=False)
        usuario.save()
        trabajador=usuario.Worker
        trabajador.especialidad=self.cleaned_data.get('especialidad')
        trabajador.rubro=self.cleaned_data['rubro']
        trabajador.certificado=self.cleaned_data['certificado']
        zone=self.cleaned_data['zonas']
        trabajador.zonas.set(zone)
        trabajador.save()
        return usuario

oficios/apps/Usuarios/forms.py
from django.forms import ModelForm
from . import models

class UsuariosForm(ModelForm):
    class Meta:
        model=models.Usuarios
        fields='__all__'

oficios/apps/Trabajadores/views.py
from django.shortcuts import render,get_object_or_404
from django.template.loader import render_to_string
from django.views import generic
from django.urls import reverse_lazy
from . import models
from . import forms
from ..Usuarios.models import Usuarios
from ..Comentarios.models import Comentarios
from ..Zonas.models import Zonas
from django.http import HttpResponse
import json
from geopy import geocoders, Nominatim #geopy obtener coordenadas a partir de una direccion

class Registro(generic.CreateView):
    template_name='Usuarios/Registro.html'
    model=models.Trabajadores
    form_class=forms.TrabajadoresForm
    success_url=reverse_lazy('login')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['usuario'] = 'Trabajador'
        return context   

class Listar(generic.ListView):
    model = models.Trabajadores
    template_name = "Usuarios/Trabajadores/Listar.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['zonas'] = Zonas.objects.all()
        return context

#Se usa el modelo Usuario ya que es el modelo usado por el form y el modelo que se instancia
#Para que django se ocupe de lo complicado
class EditarPerfil(generic.edit.UpdateView):
    template_name='Usuarios/EditarPerfil.html'
    model=Usuarios
    form_class=forms.EditarForm
    success_url=reverse_lazy('Usuarios:perfil')

class MostrarPerfil(generic.DetailView):
    model = models.Trabajadores
    template_name = 'Usuarios/Trabajadores/MostrarPerfil.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comentario'] = Comentarios.objects.filter(trabajador=context['object'])
        locator = Nominatim(user_agent="myGeocoder") #toma geopy
        location = locator.geocode(str(context["object"].usuario.address).encode('utf-8'))#toma el domicilio
        if location:
            context['coord'] = ("{}, {}".format(location.latitude, location.longitude))#transforma direccion en coordernadas
        else:
            context['mal']='Direccion no encontrada'
            zona=str(context["object"].zonas.all())
            if zona:
                location = locator.geocode(zona[0].encode('utf-8'))                
                if location:
                    context['coordZona'] = ("{}, {}".format(location.latitude, location.longitude))#transforma direccion en coordernadas

        return context

def ajaxTrabajador(request):
    if request.is_ajax():
        data={}
        zona = request.GET.get('zona',None)
        respuesta=[]
        pk=[]
        if zona.lower()=='todos':
            trabajadores=models.Trabajadores.objects.all()
        else:
            trabajadores=Zonas.objects.get(nombre=zona).Opera.all()
            
        for x in trabajadores:
            lista = [str(round(x.promedio))+'/5',str(x.usuario.first_name)+' '+str(x.usuario.last_name),x.rubro.nombre,x.especialidad,str(x.pk)]

            respuesta.append(lista)

        salida = {'datos':respuesta,'pk':pk}
        data=json.dumps(salida)
        return HttpResponse(data,'application/json')

oficios/apps/Usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse_lazy
from . import models
# Create your views here.
@login_required
def Perfil(request):
    return render(request,'Usuarios/Perfil.html')

class BorrarPerfil(generic.DeleteView):
    model = models.Usuarios
    template_name = 'Usuarios/BorrarPerfil.html'
    success_url = reverse_lazy('logout')

oficios/templates/Usuarios/Trabajadores/Listar.html
{% extends "Base.html" %}
{% block title %}
<title> Trabajadores </title>
{% endblock title %}
{% block content %}
<header class="mastbody"> </header>
    <div class="container h-100">
    <br>
    <br>
    <br>

        <div class="container table" style="border-radius: 5px; margin: 10px; padding: 10px; background-color: rgba(255, 255, 255, 0.959); filter:alpha(opacity=90); opacity:0.9;">
            <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive"> 
                            <div class="dataTables_wrapper dt-bootstrap4 no-footer">
                                <div class="filtro row">
                                    <div class="col-sm-12 col-md-6 rubro">
                                        <label for="rubro">Filtre por Rubros</label>
        
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <form method="GET" id="filtroZona" action="{% url 'Trabajadores:filtroZona' %}">
                                            <div class="form-group">
                                                <label for="zonas">Filtre por zonas</label>
                                                <select class="form-control" id="zonas">
                                                  <option>Todos</option>
                                                  {% for z in zonas %}
                                                    <option>{{z}}</option>
                                                    
                                                  {% endfor %}
                                                </select>
                                              </div>
                                              
                                     
                                          </form>
                                    </div>
        
                                </div> 
                            </div>   
                            
                            
                              <br>
                            <table id="TableT" class="display table table-hover table-bordered " style="width:100%">
                            <thead>
                                <tr>
                                    <th>Ranking</th>
                                    <th>Nombre</th>
                                    <th class="select-filter">Rubro</th>
                                    <th>Especialidad</th>
    
                                </tr>
                            </thead>
                            <tbody>
                                {% include "Usuarios/Trabajadores/Listar_table.html" %}
    
                            </tbody>  
                                 
                        </table>                  
                        </div>
                    </div>
            </div>  
        </div>
    </div>

    



{% endblock content %}

oficios/templates/Usuarios/Trabajadores/Listar_table.html
{% for object in object_list %} 
                            <tr data-url="{% url 'Trabajadores:mostrarPerfil' object.pk %}">
                            <td>{{ object.promedio|floatformat:"0" }}/5</td>
                            <td>{{ object.usuario.first_name}} {{object.usuario.last_name }}</td>

                            <td>{{ object.rubro }}</td>
                            <td>{{object.especialidad}}</td>
                            
                            
                        <!-- If objet_list is empty  -->
                            
                            </tr>
                            {% empty %} 
            
    <strong>No objects yet. </strong> 
                            {% endfor %}

oficios/templates/Usuarios/Trabajadores/MostrarPerfil.html
{% extends 'Base.html' %}
{% block title %}

<title> Perfil {{object.usuario.first_name}} </title>
{% endblock title %}

{% block content %}
<header class="mostrarPerfilHeader">
</header>
    <div class="container h-100">
        <ul class="list-group">
            <div class="jumbotron"> 
                <h2 class="display-4">Perfil: {{object.usuario.last_name}}, {{object.usuario.first_name}}</h2>
                <hr>
                <br>    
                <div class="form-row">
                    <div class="form-group col-md-4">
                        
                        
                        
                        <div class="card" style="width: 18rem;">
                            <div class="card-header">
                              Datos personales
                            </div>
                            <ul class="list-group list-group-flush">
                              <li class="list-group-item">Nombre: {{object.usuario.first_name}}</li>
                              <li class="list-group-item">Nombre: {{object.usuario.last_name}}</li>
                              <li class="list-group-item">Especialidad: {{object.especialidad}}</li>
                              <li class="list-group-item">Rubro: {{object.rubro}}</li>
                            </ul>
                          </div>
    
                    </div>
                    <div class="form-group col-md-4">
                        
                        <div class="card" style="width: 18rem;">
                            <div class="card-header">
                              Datos contacto
                            </div>
                            <ul class="list-group list-group-flush">
                              <li class="list-group-item">Telefono: {{object.usuario.phone}}</li>
                              <li class="list-group-item">Email: {{object.usuario.email}}</li>
                              <li class="list-group-item">Direccion: {{object.usuario.address}}</li>
                            </ul>
                          </div>
                        
                    </div>
                    <div class="form-group col-md-4">
                      <li class="list-group-item">Ranking: {{object.promedio|floatformat:"0" }}/5</li>
                      <br>
                      {% if not user.is_authenticated %}
                        <div class="row align-items-center justify-content-center text-center">
                          <font color="red" face="Consolas" size=4>
                            <P>PARA CALIFICAR Y COMENTAR DEBE ESTAR LOGUEADO</P>
                        </font>
                        </div>
                        
                      
                      <div class="row align-items-center justify-content-center text-center">
                        <a href="{% url 'Stalkers:registro' %}" class="btn btn-info" style="margin: 0.5rem;">
                          <i class="fas fa-user-plus"></i>Register</a>
                          <a href="{% url 'login' %}" class="btn btn-success" style="margin: 0.5rem;">
                            <i class="fas fa-sign-in-alt"></i>Login</a>
                      </div>
                          

                        {% else %}
                      <label for="coment">Califica al trabajador</label>
                      
                      <center>{% include 'Calificaciones/Calificar.html' %}</center>
                      {% endif %}
                      <br>
                      <br>
                        <div class="card" style="width: 18rem;">
                            <div class="card-header">
                              Zonas donde opera
                            </div>
                            <ul class="list-group list-group-flush">                              
                              {% for z in object.zonas.all %}
                                <li class="list-group-item">{{z}}</li>
                              {% endfor %}
                            </ul>
                          </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4" style="width: 18rem;">    
                            {%if object.certificado %}
                            <img id="myImg" src="{{object.certificado.url}}" alt="" style="max-width: 290px;">
                            {%else%}
                                <h4>   Sin Imagen....</h4>
                            {%endif%}
                    </div>          
                      {% if coord %}
                      <div class="form-group col-md-4" style="width: 18rem;">
                        <iframe src="https://maps.google.com/maps?q=@{{ coord }}&output=embed" width="280" height="280" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                   </div>
                      {% else %}
                      <div class="form-group col-md-4" style="width: 18rem;">
                        <font color="Olive" face="Comic Sans MS,arial" size=4>
                          <P>{{mal}}</P>
                      </font>
                     
                      
                      {% if coordZona %}

                        <iframe src="https://maps.google.com/maps?q=@{{ coordZona }}&output=embed" width="280" height="280" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                   
                      {% endif %}
                    </div>
                      {% endif %}
                </div>
            </div>
            <hr>
            <h3>Comentarios</h3>
            {% include 'Usuarios/Trabajadores/Mostrar_Comentarios.html' %}
            {% if not user.is_authenticated %}
            <div class="row align-items-center justify-content-center text-center">
              <font color="red" face="Consolas" size=4>
                <P>PARA CALIFICAR Y COMENTAR DEBE ESTAR LOGUEADO</P>
            </font>
            </div>
            
          
          <div class="row align-items-center justify-content-center text-center">
            <a href="{% url 'Stalkers:registro' %}" class="btn btn-info" style="margin: 0.5rem;">
              <i class="fas fa-user-plus"></i>Register</a>
              <a href="{% url 'login' %}" class="btn btn-success" style="margin: 0.5rem;">
                <i class="fas fa-sign-in-alt"></i>Login</a>
          </div>
              

            {% else %}
                
                <div class="container">
                  <div class="row">
                    <div class="col-12">
                      {% include 'Comentarios/Comentar.html' %}
                    </div>
                  </div>
                </div>
              
            {% endif %}
        </ul>
        <br><br><br>
      </div>


    <!-- The Modal -->
<div id="myModal" class="modal-image">

  <!-- The Close Button -->
  <span class="close">&times;</span>

  <!-- Modal Content (The Image) -->
  <img class="modal-image-content" id="img01">

  <!-- Modal Caption (Image Text) -->
  <div id="caption"></div>
</div>
{% endblock content %}

oficios/templates/Usuarios/Trabajadores/Mostrar_Comentarios.html
<div class="table-wrapper-scroll-y my-custom-scrollbar">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">stalker</th>
                <th scope="col">descripcion</th>
                <th scope="col">fecha</th>
            </tr>
        </thead>
        <tbody>
            {% for co in comentario %}
            <tr>            
                <td>{{co.stalker.usuario.first_name}}</td>
                <td>{{co.descripcion}}</td>
                <td>{{co.fecha_pub}}</td>  
            </tr>
            {% endfor %} 
        </tbody>
    </table>
</div>